/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myvideo_VideoPrase */

#ifndef _Included_com_myvideo_VideoPrase
#define _Included_com_myvideo_VideoPrase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myvideo_VideoPrase
 * Method:    parseName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myvideo_VideoPrase_parseName
  (JNIEnv *, jclass);

/*
 * Class:     com_myvideo_VideoPrase
 * Method:    callJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myvideo_VideoPrase_callJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
