/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myvideo_YVideo */

#ifndef _Included_com_myvideo_YVideo
#define _Included_com_myvideo_YVideo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myvideo_YVideo
 * Method:    getVideoKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myvideo_YVideo_getVideoKey
  (JNIEnv *, jclass);

/*
 * Class:     com_myvideo_YVideo
 * Method:    callJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myvideo_YVideo_callJni
  (JNIEnv *, jobject);

/*
 * Class:     com_myvideo_YVideo
 * Method:    callParam
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myvideo_YVideo_callParam
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
