/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_client_myjni_MyJni */

#ifndef _Included_com_client_myjni_MyJni
#define _Included_com_client_myjni_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_client_myjni_MyJni
 * Method:    sum
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_client_myjni_MyJni_sum
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
